version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - traefik
    environment:
      - MONGODB_URI=${MONGODB_URI}
    labels:
      - "traefik.http.routers.backend.rule=(Host(`rollback.localhost`) && PathPrefix(`/backend`))"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/backend"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - REACT_APP_MAPBOX_TOKEN=${REACT_APP_MAPBOX_TOKEN}
    labels:
      - "traefik.http.routers.frontend.rule=Host(`rollback.localhost`)"

networks:
  default:
    external:
      name: github_rollback_default
    
